# Generated by Django 2.2.4 on 2019-08-05 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_upload'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='like_video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='video.Video'),
        ),
    ]
