# Generated by Django 2.2.4 on 2019-08-05 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_profile_like_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='like_video',
        ),
    ]
