# Generated by Django 2.2.1 on 2019-08-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utitle', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('ubody', models.TextField()),
                ('uvideo', models.FileField(null=True, upload_to='uploads/%Y/%m/%d')),
            ],
        ),
    ]
