# Generated by Django 2.2.4 on 2019-08-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20190805_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='uname',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
