# Generated by Django 2.2.1 on 2019-08-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_upload_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='author',
            field=models.TextField(null=True),
        ),
    ]
