# Generated by Django 2.1.1 on 2019-08-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_video_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='author',
            field=models.CharField(default='작성자', max_length=200),
        ),
    ]
