# Generated by Django 2.2.4 on 2019-08-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_video_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='vhits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
