# Generated by Django 2.2.4 on 2019-08-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_video_vhits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vhits',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
