# Generated by Django 2.2.1 on 2019-08-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20190808_1545'),
        ('video', '0008_auto_20190808_1756'),
    ]

    operations = [
    ]
