# Generated by Django 2.1.1 on 2019-08-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_auto_20190808_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='author',
            field=models.CharField(blank=True, default='작성자', max_length=200),
        ),
    ]
