# Generated by Django 2.2.1 on 2019-08-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_merge_20190808_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='author',
            field=models.CharField(default='작성자', max_length=200),
        ),
    ]
