# Generated by Django 2.2.1 on 2019-08-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_auto_20190808_2132'),
        ('video', '0010_auto_20190808_2147'),
    ]

    operations = [
    ]
