# Generated by Django 2.2.4 on 2019-08-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_auto_20190808_2147'),
        ('video', '0010_auto_20190808_2132'),
    ]

    operations = [
    ]
