# Generated by Django 2.2.4 on 2019-08-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_merge_20190809_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='author',
            field=models.CharField(blank=True, default='작성자', max_length=200),
        ),
    ]
