# Generated by Django 2.2.4 on 2019-08-09 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_merge_20190809_0950'),
        ('video', '0012_auto_20190809_1655'),
    ]

    operations = [
    ]
