# Generated by Django 2.2.1 on 2019-08-10 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0013_merge_20190809_2153'),
        ('video', '0013_merge_20190809_1814'),
    ]

    operations = [
    ]
